name-template: 'Actions Monorepo v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH'
commitish: main
filter-by-commitish: true
template: |
 GitHub Actions Monorepo, version $RESOLVED_VERSION
 
 ## Changes
 
 $CHANGES
  
 **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

branches:
  - main

categories:
  - title: 'Actions Updates'
    labels:
      - 'impacts:actions'
    collapse-after: 10
  - title: 'New Features'
    labels:
      - 'enhancement'
    collapse-after: 10
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'type:fix'
    collapse-after: 3
  - title: 'Repo Updates'
    labels:
      - 'impacts:repo'
    collapse-after: 3
  - title: 'Documentation'
    labels:
      - 'documentation'
      - 'type:docs'
    collapse-after: 5
  - title: '🧰 Maintenance'
    labels:
      - 'type:chore'
      - 'type:refactor'

category-template: "### $TITLE"
#change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

exclude-labels:
  - 'skip-changelog'
  - 'actions:autorelease'

exclude-contributors:
  - 'rw-actions-bot[bot]'

prerelease-identifier: 'rc'

replacers:
  - search: '/CVE-(\d{4})-(\d+)/g'
    replace: 'https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-$1-$2'
  - search: 'myname'
    replace: 'My Name'
  # remove commit message prefixes from release notes
  - search: '/^(fix|feat|ci|docs)?: /g'
    replace: ''
  # remove commit message prefixes, including scope, from release notes
  # but attempt to put the 'scope' (regex group 2) back into the notes
  - search: '/^(fix|feat|ci|docs)(\(.+?\))?: /g'
    #replace: ''
    replace: '$2: '
  # find breaking changes and include 'breaking' in the notes
  - search: '/^(fix|feat|ci|docs)?!?: /g'
    replace: 'breaking: '
  # find breaking changes and include 'breaking' in the notes
  # but attempt to put the 'scope' (regex group 2) back into the notes
  - search: '/^(fix|feat|ci|docs)(\(.+?\))?!?: /g'
    replace: 'breaking($2): '

version-resolver:
  major:
    labels:
      - 'version:major'
  minor:
    labels:
      - 'version:minor'
      #- 'type:feat'
  patch:
    labels:
      - 'version:patch'
      - 'type:feat'
      - 'type:fix'
      - 'type:docs'
      - 'type:style'
      - 'type:refactor'
      - 'type:perf'
      - 'type:test'
      - 'type:build'
      - 'type:ci'
      - 'type:chore'
      - 'type:revert'
      - 'type:change'
      - 'type:deprecate'
      - 'type:remove'
      - 'type:security'
  default: 'patch'


