# https://www.mkdocs.org/user-guide/configuration/
site_name: Actions monorepo
site_url: https://rwaight.github.io/actions
site_author: rwaight
repo_url: https://github.com/rwaight/actions
repo_name: rwaight/actions

# this site uses https://github.com/lukasgeiter/mkdocs-awesome-nav for navigation
  ## the plugin won't do anything if `mkdocs.yml` defines a `nav` or `pages` entry
  ## https://lukasgeiter.github.io/mkdocs-awesome-nav/features/nav/
  # nav:
  #   - Home: 'index.md'
  #   # https://www.mkdocs.org/user-guide/configuration/#nav
  #   # https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
  ## use https://github.com/lukasgeiter/mkdocs-awesome-nav for navigation
  ## https://lukasgeiter.github.io/mkdocs-awesome-nav/features/nav/

# https://www.mkdocs.org/user-guide/configuration/#theme
theme:
  name: material
  #locale: en
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#automatic-hiding
    - header.autohide
    # https://squidfunk.github.io/mkdocs-material/plugins/blog/#navigation
    - navigation.indexes
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#setting-up-navigation
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    # do not use 'navigation.tabs' in the 'rwaight/actions' repo
    #- navigation.tabs
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    - content.action.edit
    # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#linked-content-tabs
    - content.tabs.link
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
    - content.code.copy
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-selection-button
    - content.code.select
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations
    - content.code.annotate
    #
  icon:
    # # https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/?h=icon#favicon
    # favicon: 
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/?h=icon#logo
    logo: simple/github
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository-icon
    repo: fontawesome/brands/git-alt
    #repo: octicons/mark-github-24
  language: en    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language
  palette:
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette
    scheme: slate

# https://www.mkdocs.org/user-guide/configuration/#docs_dir
docs_dir: 'docs'

# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
# the edit_uri should include configuring the 'content.action.edit' plugin
#edit_uri: edit/main/docs/
# testing 'blob/main/docs/' instead of 'edit/main/docs/'
edit_uri: blob/main/docs/

markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#betterem
  # https://facelessuser.github.io/pymdown-extensions/extensions/betterem/
  - pymdownx.betterem
  # # https://oprypin.github.io/markdown-callouts/index.html#markdown-callouts
  # # will need to install with 'pip install markdown-callouts' in 'publish.yml'
  # - callouts
  ###
  # not sure if 'pymdownx.github' works
  #- pymdownx.github
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#definition-lists
  #- def_list
  # https://squidfunk.github.io/mkdocs-material/reference/diagrams/#configuration
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # https://squidfunk.github.io/mkdocs-material/reference/lists/#using-task-lists
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#tasklist
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      title: On this page
      permalink: true
  # https://squidfunk.github.io/mkdocs-material/reference/formatting/#configuration
  # support for sub and superscripts
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde


# https://www.mkdocs.org/user-guide/configuration/#plugins
plugins:
  # https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#built-in-privacy-plugin
  - privacy
  # https://github.com/lukasgeiter/mkdocs-awesome-nav
  - awesome-nav
  - search
  # the blog plugin is NOT enabled for the 'actions' repo
  # # https://squidfunk.github.io/mkdocs-material/plugins/blog/
  # - blog:
  #     # https://squidfunk.github.io/mkdocs-material/plugins/blog/#general
  #     enabled: true
  #     blog_dir: blog
  #     blog_toc: true
  #     # https://squidfunk.github.io/mkdocs-material/plugins/blog/#posts
  # https://squidfunk.github.io/mkdocs-material/plugins/tags/
  - tags:
      enabled: true
      # https://squidfunk.github.io/mkdocs-material/plugins/tags/#config.tags_file
      # https://github.com/lukasgeiter/mkdocs-awesome-nav/issues/102
      tags_file: plugins/tags.md
      # # https://squidfunk.github.io/mkdocs-material/plugins/tags/?h=tags+allowed#config.tags_allowed
      # # 'tags_allowed' is for sponsors only
      # tags_allowed:
      #   - GitHub
      #   - Jekyll
      #   - Linux
      #   - MacOS
      #   - MkDocs
      #   - Virtualization
      # # https://squidfunk.github.io/mkdocs-material/plugins/tags/?h=tags+allowed#config.tags_hierarchy
      # # 'tags_hierarchy' is for sponsors only
      # tags_hierarchy: true
      # By default, tags are separated by a forward slash `/`, but you can change this to any string, e.g., `.`
      # https://squidfunk.github.io/mkdocs-material/plugins/tags/#config.tags_hierarchy_separator
  - git-committers:
      # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-contributors
      # https://github.com/ojacques/mkdocs-git-committers-plugin-2
      repository: rwaight/actions
      branch: main
      # https://github.com/ojacques/mkdocs-git-committers-plugin-2/pull/79
      exclude_committers:
        - web-flow
      exclude:
        - index.md
        - blog/index.md
        - test-*.md
        - '!**/index.md'
      # allow the plugin to be disabled locally by setting the environment variable 'ENABLE_GIT_COMMITTERS' to 'false'
      # use 'ENABLE_GIT_COMMITTERS=false mkdocs serve' to run mkdocs and disable the plugin locally
      enabled: !ENV [ENABLE_GIT_COMMITTERS, true]   # defaults to true

