name: label-sync
author: Federico Grandi <federicograndi@duck.com>
description: An action that allows you to sync labels from a repository or a config file
group: github
imported: true
local:
  modifications: false
  update:
    exclusions:
      - README-examples.md
      - README.md
      - example-custom-notes.md
source:
  action_name: label-sync
  author: EndBug
  repo_name: label-sync
  repo_url: https://github.com/EndBug/label-sync
  current_version: v2.3.3
  latest_version: v2.3.3
  update_available: false
specs:
  action_file: action.yml
  inputs: [token, config-file, source-repo, request-token, delete-other-labels, dry-run]
  outputs: []
  runs:
    using: node16
    main: lib/index.js
tests:
  _comment: reserved for future use
