name: 'Table Actions'
description: 'Updates GitHub project tables based on issues'
branding:
  icon: 'activity'
  color: 'blue'
  # Ref: https://haya14busa.github.io/github-action-brandings/
  # fork: https://github.com/rwaight/github-action-brandings
inputs:
  config:
    description: 'A JSON array of objects containing label and tableNumber'
    required: true
  ghToken:
    description: 'A GitHub token with write access to the destination project and read access to the source issue. See https://docs.github.com/en/actions/reference/encrypted-secrets'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
