name: projectnext-label-assigner
author: richkuz
description: Updates GitHub project tables based on issues
group: github
imported: true
local:
  modifications: true
source:
  action_name: projectnext-label-assigner
  author: richkuz
  repo_name: projectnext-label-assigner
  repo_url: https://github.com/richkuz/projectnext-label-assigner
  current_version: 1.1.0
  latest_version: 1.1.0
  update_available: true
specs:
  action_file: action.yml
  inputs: [config, ghToken]
  outputs: []
  runs:
    using: node12
    main: dist/index.js
tests:
  _comment: reserved for future use
