name: find-pull-request
author: juliangruber
description: A GitHub Action for finding pull requests
group: github
imported: true
local:
  modifications: false
source:
  action_name: find-pull-request
  author: juliangruber
  repo_name: find-pull-request-action
  repo_url: https://github.com/juliangruber/find-pull-request-action
  current_version: v1.9.0
  latest_version: v1.9.0
  update_available: false
specs:
  action_file: action.yml
  inputs: [github-token, branch, base, author, state, repo, sort, direction, labels]
  outputs: [number, title, url, head-ref, head-sha, base-ref, base-sha, base-repo, state]
  runs:
    using: node20
    main: dist/index.js
tests:
  _comment: reserved for future use
