name: update-json-field
description: Update a specific field in a JSON file
group: utilities
imported: false
local:
  author: rwaight
  modifications: true
  update:
    exclusions:
      - README-examples.md
specs:
  action_file: action.yml
  inputs: [json-file, vars-field, vars-new-value, verbose]
  outputs: [previous-value, new-value]
  runs:
    using: composite
tests:
  _comment: reserved for future use
