name: render-template
author: Konstantin Chukhlomin <mail@chuhlomin.com>
description: Renders file based on template and passed variables
group: utilities
imported: true
local:
  modifications: false
  update:
    exclusions:
      - README-examples.md
      - example-custom-notes.md
source:
  action_name: render-template
  author: chuhlomin
  repo_name: render-template
  repo_url: https://github.com/chuhlomin/render-template
  current_version: v1.10
  latest_version: v1.10
  update_available: false
specs:
  action_file: action.yml
  inputs: [template, vars, vars_path, result_path, timezone]
  outputs: [result]
  runs:
    using: docker
tests:
  _comment: reserved for future use
