# Require users to select an issue template with `blank_issues_enabled: false`
blank_issues_enabled: false
contact_links:
  - name: GitHub Actions Monorepo
    url: https://github.com/rwaight/actions
    about: Please report all related issues to the actions here.
