# This file is sourced from https://github.com/rwaight/actions/tree/main/assets/copycat
# This workflow runs 'export-and-sync-labels'
name: Label Manager
run-name: Run ${{ github.event.action || 'label manager' }} from ${{ github.event_name }}
on: 
  #push:
  #  branches: [main]
  #  paths: ['assets/my-labels-*.yml']
  repository_dispatch:
    types: [export-labels,sync-labels]
  # You can run this with every event, but it's better to run it only when you actually need it.
  workflow_dispatch:
    inputs:
      export_labels:
        description: 'Export labels from repo'
        required: true
        default: true
        type: boolean
      sync_labels:
        description: 'Sync labels from config files'
        required: true
        default: false
        type: boolean
      verbose_output:
        description: 'Verbose output'
        required: true
        default: false
        type: boolean
  schedule:
    - cron: '0 10 1 */6 *'  # export labels once every six months, at 10:00 on the first of the month

env:
  #VERBOSE_WORKFLOW: ${{ inputs.verbose_output || 'false' }}
  INFRA_SOURCE: rwaight/actions
  INFRA_BOT: rw-actions-bot[bot]

jobs:
  export-and-sync-labels:
    name: Export and sync repo labels
    runs-on: ubuntu-latest
    env:
      VERBOSE_WORKFLOW: ${{ inputs.verbose_output || 'false' }}
    permissions:
      contents: write
      issues: write
    steps:
      - name: Exit workflow in forked repo
        id: check-repo-owner
        if: (github.repository_owner != 'rwaight')
        run: |
          echo "This workflow was run in a forked repo. Unless this file is updated, none of the jobs will run. "
          echo "This workflow will now exit. "
          echo "::error file=label-manager,title=⛔ error::This workflow was run in a forked repo."
          exit 1

      # Create a GitHub App Token from actions/create-github-app-token
      # https://github.com/actions/create-github-app-token
      - name: Create an App Token for this job
        id: app-token
        if: | 
          (github.event_name=='repository_dispatch' && github.event.action=='sync-labels') || 
          (github.event_name=='workflow_dispatch' && inputs.sync_labels==true)
        #uses: actions/create-github-app-token@v1.10.0
        uses: actions/create-github-app-token@a0de6af83968303c8c955486bf9739a57d23c7f1
        with:
          # required
          app-id: ${{ secrets.RW_ACTIONS_APP_ID }}
          private-key: ${{ secrets.RW_ACTIONS_APP_KEY }}
          # create a token for all repositories in the current owner's installation
          owner: ${{ github.repository_owner }}

      - name: Checkout files from commit tree
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}

      - name: Configure Git Credentials if using the app token
        id: configure-git
        if: ${{ steps.app-token.outputs.token }}
        run: |
          ##
          ## Configure git to login as the RW Actions Bot.
          git config user.name ${{ env.INFRA_BOT }}
          git config user.email ${{ secrets.RW_ACTIONS_BOT_UID }}+rw-actions-bot[bot]@users.noreply.github.com
        ## previous 'run' commands
          ##git config user.name rw-actions-bot[bot]

      - name: Export label config using rwaight/actions/github/export-label-config
        id: export-label-config
        if: |
          (github.event_name=='schedule' && github.event.schedule=='0 10 1 */6 *') || 
          (github.event_name=='workflow_dispatch' && inputs.export_labels==true) || 
          (github.event_name=='repository_dispatch' && github.event.action=='export-labels') ||
          (github.event_name=='repository_dispatch' && github.event.action=='sync-labels') || 
          (github.event_name=='workflow_dispatch' && inputs.sync_labels==true)
        uses: rwaight/actions/github/export-label-config@v0.1.34   # can use version specific or main
        #uses: rwaight/actions/github/export-label-config@main  # can use version specific or main
        with:
          # This is needed if you're dealing with private repos.
          token: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
          # Set 'raw-result' to `true` if you want to get the raw API reponse. Defaults to `false`.
          raw-result: false
          # By default every label entry will have an `aliases` property set to an empty array.
          # It's for EndBug/label-sync, if you don't want it you can set this to `false`
          add-aliases: true

      - name: Sync labels using rwaight/actions/github/label-sync
        id: run-label-sync
        if: | 
          steps.export-label-config.outcome == 'success' && (
          (github.event_name=='repository_dispatch' && github.event.action=='sync-labels') || 
          (github.event_name=='workflow_dispatch' && inputs.sync_labels==true)
          )
        uses: rwaight/actions/github/label-sync@v0.1.34 # can use version specific or main
        #uses: rwaight/actions/github/label-sync@main # can use version specific or main
        with:
          config-file: |
            https://raw.githubusercontent.com/rwaight/actions/main/assets/my-labels-core.yml
            https://raw.githubusercontent.com/rwaight/actions/main/assets/my-labels-actions.yml
            https://raw.githubusercontent.com/rwaight/actions/main/assets/my-labels-versioning.yml
          ##  assets/my-labels-core.yml
          ##  assets/my-labels-actions.yml
          ##  assets/my-labels-versioning.yml
          #
          # The 'request-token' parameter is needed so the remote config-file values can be accessed
          request-token: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
          # If you want to delete any additional label, set this to true
          delete-other-labels: true
          # If you want the action just to show you the preview of the changes, without actually editing the labels, set this to true
          dry-run: false
          # You can change the token used to change the labels, this is the default one
          token: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}

      - name: Verbose | Output workflow information
        id: run-workflow-verbose
        if: env.VERBOSE_WORKFLOW=='true'
        run: |
          echo "workflow verbose was set to true... you should probably put something here for verbose purposes. "
          echo ""
          echo "The GitHub event_name is: ${{ github.event_name }}"
          echo "The GitHub ref is: ${{ github.ref }}"
          echo "The GitHub ref_name is: ${{ github.ref_name }}"
          echo ""
          echo "For more information, see the GitHub Actions Contexts docs, which are located at: "
          echo "https://docs.github.com/en/actions/learn-github-actions/contexts#github-context"
          echo "The 'run-workflow-verbose' step is now complete. "
        continue-on-error: true
