name: Install Instruqt CLI
description: Installs the Instruqt CLI into the GitHub Runner
author: rwaight

inputs:
  version:
    description: >-
      The version of the Instruqt CLI to be used, defaults to latest.
      If a different version is needed, use a valid release tag from https://github.com/instruqt/cli/tags
    required: false
    default: 'latest'
  verbose:
    description: 'Determine if the action should run verbose tasks, defaults to false.'
    required: false
    default: 'false'

runs:
  using: composite
  steps:

    - name: Validate that the runner OS is Linux
      if: ${{ runner.os != 'Linux' }}
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message
      run: |
        echo "error in the action '${{ github.action }}' at file path: '${{ github.action_path }}' "
        echo "::error file=instruqt/install-cli/action.yml,title=⛔ Install Instruqt CLI error hint::This action supports Linux only"
        exit 1
      shell: bash

    - name: Verbose | Greet the triggering_actor
      if: inputs.verbose=='true'
      run: echo Hello ${{ github.triggering_actor }}, the verbose variable is set to true.
      shell: bash

    - name: Verbose | Print the inputs
      if: inputs.verbose=='true'
      id: verbose-print-inputs
      run: | 
        ## Print the inputs if inputs.verbose=='true'
        ## the double number signs below are for line spacing and readability only
        ##
        echo "version is set to '${{ inputs.version }}' "
        echo "verbose is set to '${{ inputs.verbose }}' "
        ##
      shell: bash

    - name: Download the latest instruqt-cli zip
      id: download-latest-zip
      if: inputs.version=='latest'
      run: |
        echo "::group::starting the 'download-latest-zip' step... "
        echo ""
        curl -L https://github.com/instruqt/cli/releases/latest/download/instruqt-linux.zip -o instruqt.zip
        echo "instruqt-cli zip downloaded"
        echo ""
        echo "finishing the 'download-latest-zip' step... "
        echo "::endgroup::"
      shell: bash

    - name: Download the ${{ inputs.version }} instruqt-cli zip
      id: download-versioned-zip
      if: inputs.version!='latest'
      run: |
        echo "::group::starting the 'download-versioned-zip' step... "
        echo ""
        echo "the version ${version} was specified and will be downloaded"
        curl -L https://github.com/instruqt/cli/releases/download/${{ inputs.version }}/instruqt-linux.zip -o instruqt.zip
        echo "instruqt-cli zip downloaded"
        echo ""
        echo "finishing the 'download-versioned-zip' step... "
        echo "::endgroup::"
      env:
        version: ${{ inputs.version }}
      shell: bash

    - name: Configure instruqt-cli executable
      id: configure-instruqt-cli
      run: |
        echo "::group::starting the 'configure-instruqt-cli' step... "
        echo ""
        unzip instruqt.zip
        sudo cp instruqt /usr/local/bin
        sudo chmod +x /usr/local/bin/instruqt
        echo "instruqt-cli installed"
        echo ""
        echo "finishing the 'configure-instruqt-cli' step... "
        echo "::endgroup::"
      shell: bash

branding:
  # Ref: https://haya14busa.github.io/github-action-brandings/
  # fork: https://github.com/rwaight/github-action-brandings
  icon: download
  color: blue
