name: build-mkdocs-material
description: A composite action to build Material for MkDocs.
group: builders
imported: false
local:
  author: rwaight
  modifications: true
specs:
  action_file: action.yml
  inputs: [gh-token, plugins, python-version, verbose]
  outputs: [install-summary]
  runs:
    using: composite
tests:
  _comment: reserved for future use
