name: packer-skip-create
author: rwaight
description: Determine the Packer skip-create option based on predetermined conditions. This action is used with Packer to determine the `skip_create*` variable for either Amazon EBS (`skip_create_ami`) or Google Cloud Platform (`skip_create_image`).
group: vars
imported: false
local:
  author: rwaight
  modifications: true
  update:
    exclusions:
      - README-examples.md
      - example-custom-notes.md
source:
  action_name: vars-packer-skip-create
  author: rwaight
  latest_version: "null"
  update_available: false
  repo_name: actions
  repo_url: https://github.com/rwaight/actions
specs:
  action_file: action.yml
  inputs: [create-image, event-name, ref, ref-name, ref-type, release-tag-name, workflow, workflow-summary, verbose]
  outputs: [image-skip-create, image-skip-note, image-skip-reason]
  runs:
    using: composite
tests:
  _comment: reserved for future use
