name: set-version
author: rwaight
description: 'Determine a build version using git describe.'
group: builders
imported: false
local:
  author: rwaight
  modifications: true
specs:
  action_file: action.yml
  inputs: [checkout, gh-token, strategy, verbose]
  outputs: [build-version]
  runs:
    using: composite
tests:
  _comment: reserved for future use
