name: 'Get an app token in an Actions workflow.'
description: Useful for remedying the problem of restricted access tokens, especially on PRs from forks.
author: Hamel Husain
inputs:
  APP_PEM:
    description: a base64 encoded string version of your PEM file used to authenticate as a GitHub App.  You can apply this encoding in the terminal `cat key.pem | base64`
    required: true
  APP_ID:
    description: you GITHUB App ID.
    required: true
outputs:
  app_token:
    description: The installation access token for the GitHub App corresponding to and the current repository.
branding:
  icon: 'unlock'
  color: 'blue'
  # Ref: https://haya14busa.github.io/github-action-brandings/
  # fork: https://github.com/rwaight/github-action-brandings

## this works, but the container is old and needs to be updated
##runs:
##  using: 'docker'
##  image: 'docker://docker.elastic.co/docs/app-token'

# this does not fail when building the container each time, however
# it is not working as it is not passing the token at the end
runs:
  using: 'docker'
  #image: 'Dockerfile'
  image: 'prebuild.Dockerfile'

# this will require login to ghcr.io before, using docker/login-action
#runs:
#  using: 'docker'
#  image: 'docker://ghcr.io/rwaight/actions/github/actions-app-token:latest'
