name: import-config-maintenance
author: rwaight
description: Scan actions and update/create import-config.yml files for all actions in the monorepo
group: utilities
imported: false

local:
  author: rwaight
  modifications: true
  update:
    exclusions:
      - README-examples.md
      - example-custom-notes.md

specs:
  action_file: action.yml
  inputs: [dry-run, create-new-configs, working-directory, verbose]
  outputs: [actions-processed, actions-updated, errors-found, error-log-path]
  runs:
    using: composite

tests:
  _comment: reserved for future use
