name: packer
author: Robert Anderson <riznob@gmail.com>
description: Run packer build on a template file
group: utilities
imported: true
local:
  modifications: false
source:
  action_name: packer-docker
  author: riznob
  repo_name: packer-build-action
  repo_url: https://github.com/riznob/packer-build-action
  current_version: v1.5
  latest_version: v1.5
  update_available: false
specs:
  action_file: action.yml
  inputs: [templateFile, varFile, workingDir]
  outputs: []
  runs:
    using: docker
tests:
  _comment: reserved for future use
