name: repo-version-info
author: rwaight
description: Provide version information from a git repo
group: git
imported: false
local:
  author: rwaight
  modifications: true
  update:
    exclusions:
      - README-examples.md
      - example-custom-notes.md
specs:
  action_file: action.yml
  inputs: [gh-token, include-drafts, include-pre-releases, my_workflow_debug, pre-release-id, strategy]
  outputs: [latest-release, latest-tag, version]
  runs:
    using: composite
tests:
  _comment: reserved for future use
