name: label-manager
author: Benjamin Lannon <benjamin@lannonbr.com>
description: Will update repo's labels based on data in JSON file located at $REPO/.github/labels.json
group: github
imported: true
local:
  modifications: true
  update:
    exclusions:
      - README-examples.md
      - example-custom-notes.md
source:
  action_name: label-manager
  author: lannonbr
  repo_name: issue-label-manager-action
  repo_url: https://github.com/lannonbr/issue-label-manager-action
  current_version: 4.0.0
  latest_version: 4.0.0
  update_available: false
specs:
  action_file: action.yml
  inputs: [delete]
  outputs: []
  runs:
    using: node20
    main: lib/index.js
tests:
  _comment: reserved for future use
