name: 'GitHub Runner Debug'
description: 'An action to check if the GitHub Runner is in Debug Mode.'
author: 'rwaight'
inputs:
  verbose:
    description: 'Determine if the action should run verbose tasks, defaults to false.'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:

    - name: Validate that the runner OS is Linux
      if: ${{ runner.os != 'Linux' }}
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message
      run: |
        echo "::error title=⛔ error hint::This action supports Linux only"
        exit 1
      shell: bash

    - name: Greet the triggering_actor
      if: inputs.verbose=='true' || ${{ runner.debug == '1' }}
      run: |
        echo "Hello ${{ github.triggering_actor }}, the verbose variable is set to true."
      shell: bash

    - name: GitHub Runner Debug Mode
      #if: inputs.verbose=='true' || ${{ runner.debug == '1' }}
      # to do:  run this if either the verbose input is true or the runner.debug is true
      id: runner-debug-mode
      ## The 'runner.*' and 'RUNNER_*' variables are not available in the WORKFLOW env context or the top-level JOB context, but are available in the STEP env context
      env:
        EVAL_GH_VAR_RUNNER_DEBUG_EQ0: ${{ runner.debug == '0' }}
        EVAL_GH_VAR_RUNNER_DEBUG_EQ1: ${{ runner.debug == '1' }}
        FOOBAR: ${{ runner.debug == '1' && 'foo' || 'bar' }}
        # https://github.com/actions/runner/issues/2204#issuecomment-1287947031
        # https://github.com/orgs/community/discussions/27627#discussioncomment-3302259
        GH_RUNNER_LOG: "${{ runner.debug == '1' && 'INFO' || 'ERROR' }}"
        GH_VAR_RUNNER_DEBUG1: ${{ runner.debug }}
        GH_VAR_RUNNER_DEBUG2: ${{ env.RUNNER_DEBUG }}
        GH_VAR_RUNNER_OS1: ${{ runner.os }}
        GH_VAR_RUNNER_OS2: ${{ env.RUNNER_OS }}
        GH_VAR_RUNNER_ARCH1: ${{ runner.arch }}
        GH_VAR_RUNNER_ARCH2: ${{ env.RUNNER_ARCH }}
      run: |
        echo "::group::starting the 'runner-debug-mode' step... "
        echo ""
        echo "NOTE: The 'runner.*' and 'RUNNER_*' variables are not available in the WORKFLOW env context or the top-level JOB context, but are available in the STEP env context "
        echo ""
        echo "eval if the 'runner.debug' is set to either '0' or '1' "
        echo "     runner.debug equal 0:  ${EVAL_GH_VAR_RUNNER_DEBUG_EQ0} "
        echo "     runner.debug equal 1:  ${EVAL_GH_VAR_RUNNER_DEBUG_EQ1} "
        echo ""
        echo "set FOOBAR to 'foo' if 'runner.debug' is '1'; otherwise set FOOBAR to 'bar' "
        echo "    FOOBAR:  ${FOOBAR} "
        echo ""
        echo "set GH_RUNNER_LOG to 'INFO' if 'runner.debug' is '1'; otherwise set GH_RUNNER_LOG to 'ERROR' "
        echo "    GH_RUNNER_LOG:  ${GH_RUNNER_LOG} "
        echo ""
        echo "the values of 'runner.debug' and 'env.RUNNER_DEBUG': "
        echo "    GH_VAR_RUNNER_DEBUG1:  ${GH_VAR_RUNNER_DEBUG1} "
        echo "    GH_VAR_RUNNER_DEBUG2:  ${GH_VAR_RUNNER_DEBUG2} "
        echo ""
        echo "the values of 'runner.os' and 'env.RUNNER_OS': "
        echo "    GH_VAR_RUNNER_OS1:  ${GH_VAR_RUNNER_OS1} "
        echo "    GH_VAR_RUNNER_OS2:  ${GH_VAR_RUNNER_OS2} "
        echo ""
        echo "the values of 'runner.arch' and 'env.RUNNER_ARCH': "
        echo "    GH_VAR_RUNNER_ARCH1:  ${GH_VAR_RUNNER_ARCH1} "
        echo "    GH_VAR_RUNNER_ARCH2:  ${GH_VAR_RUNNER_ARCH2} "
        echo ""
        echo "finishing the 'runner-debug-mode' step... "
        ##
        echo "::endgroup::"
      ## The 'runner.*' and 'RUNNER_*' variables are not available in the WORKFLOW env context or the top-level JOB context, but are available in the STEP env context
      shell: bash

    - name: Dump GitHub context
      id: print-github-context
      # https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#example-printing-context-information-to-the-log
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "::group::starting the 'print-github-context' step... "
        echo ""
        echo "$GITHUB_CONTEXT"
        echo ""
        echo "finishing the 'print-github-context' step... "
        ##
        echo "::endgroup::"
      shell: bash

    - name: Dump job context
      id: print-job-context
      # https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#example-printing-context-information-to-the-log
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: |
        echo "::group::starting the 'print-job-context' step... "
        echo ""
        echo "$JOB_CONTEXT"
        echo ""
        echo "finishing the 'print-job-context' step... "
        ##
        echo "::endgroup::"
      shell: bash

    - name: Dump steps context
      id: print-steps-context
      # https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#example-printing-context-information-to-the-log
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: |
        echo "::group::starting the 'print-steps-context' step... "
        echo ""
        echo "$STEPS_CONTEXT"
        echo ""
        echo "finishing the 'print-steps-context' step... "
        ##
        echo "::endgroup::"
      shell: bash

    - name: Dump runner context
      id: print-runner-context
      # https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#example-printing-context-information-to-the-log
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: |
        echo "::group::starting the 'print-runner-context' step... "
        echo ""
        echo "$RUNNER_CONTEXT"
        echo ""
        echo "finishing the 'print-runner-context' step... "
        ##
        echo "::endgroup::"
      shell: bash

    - name: Dump strategy context
      id: print-strategy-context
      # https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#example-printing-context-information-to-the-log
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: |
        echo "::group::starting the 'print-strategy-context' step... "
        echo ""
        echo "$STRATEGY_CONTEXT"
        echo ""
        echo "finishing the 'print-strategy-context' step... "
        ##
        echo "::endgroup::"
      shell: bash

    - name: Dump matrix context
      id: print-matrix-context
      # https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#example-printing-context-information-to-the-log
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: |
        echo "::group::starting the 'print-matrix-context' step... "
        echo ""
        echo "$MATRIX_CONTEXT"
        echo ""
        echo "finishing the 'print-matrix-context' step... "
        ##
        echo "::endgroup::"
      shell: bash

branding:
  # Ref: https://haya14busa.github.io/github-action-brandings/
  # fork: https://github.com/rwaight/github-action-brandings
  icon: 'edit'
  color: 'blue'
