name: GitHub Runner Debug
description: An action to check if the GitHub Runner is in Debug Mode.
group: github
imported: false
local:
  author: rwaight
  modifications: true
specs:
  action_file: action.yml
  inputs: [verbose]
  outputs: []
  runs:
    using: composite
tests:
  _comment: reserved for future use
