name: runner-debug
description: placeholder
group: github
imported: false
local:
  author: rwaight
  modifications: true
specs:
  action_file: action.yml
  inputs: [verbose]
  outputs: []
  runs:
    using: composite
tests:
  _comment: reserved for future use
