name: 'Git describe semver'
description: ''
inputs:
  fallback:
    description: 'fallback'
    default: 'v0.0.0'
  drop-prefix:
    description: 'drop-prefix'
    default: 'false'
  prerelease-prefix:
    description: 'prerelease-suffix'
    default: 'dev'
  prerelease-suffix:
    description: 'prerelease-suffix'
    default: ''
  prerelease-timestamped:
    description: 'prerelease-timestamped'
    default: 'false'
outputs:
  version:
    description: 'version'
    value: ${{ steps.git-describe-semver.outputs.version }}
runs:
  using: 'composite'
  steps:
    - uses: docker://ghcr.io/choffmeister/git-describe-semver:latest
      id: git-describe-semver
      with:
        args: >-
          --fallback="${{ inputs.fallback }}"
          --drop-prefix="${{ inputs.drop-prefix }}"
          --prerelease-prefix="${{ inputs.prerelease-prefix }}"
          --prerelease-suffix="${{ inputs.prerelease-suffix }}"
          --prerelease-timestamped="${{ inputs.prerelease-timestamped }}"
          --format="version=<version>"
          $GITHUB_OUTPUT
    - run: echo ${{ steps.git-describe-semver.outputs.version }}
      shell: bash
