name: release-drafter
author: release-drafter
description: Drafts your next release notes as pull requests are merged into master.
group: releases
imported: true
local:
  modifications: false
source:
  action_name: release-drafter
  author: release-drafter
  repo_name: release-drafter
  repo_url: https://github.com/release-drafter/release-drafter
  current_version: v5.25.0
  latest_version: v6.0.0
  update_available: true
specs:
  action_file: action.yml
  inputs: [config-name, name, tag, version, publish, latest, prerelease, prerelease-identifier, commitish, header, footer, disable-releaser, disable-autolabeler]
  outputs: [id, name, tag_name, body, html_url, upload_url, major_version, minor_version, patch_version, resolved_version]
  runs:
    using: node16
    main: dist/index.js
tests:
  _comment: reserved for future use
