name: export-label-config
author: Federico Grandi <fgrandi30@gmail.com>
description: An action that lets you generate a file containing your label settings for the current repo
group: github
imported: true
local:
  modifications: true
  update:
    exclusions:
      - README-examples.md
      - example-custom-notes.md
source:
  action_name: export-label-config
  author: EndBug
  repo_name: export-label-config
  repo_url: https://github.com/EndBug/export-label-config
  current_version: v1.0.1
  latest_version: v1.0.1
  update_available: false
specs:
  action_file: action.yml
  inputs: [token, raw-result, add-aliases]
  outputs: []
  runs:
    using: node20
    main: lib/index.js
tests:
  _comment: reserved for future use
