name: Install yq
description: Installs the yq package for parsing YAML files
author: 'instruqt'

inputs:
  version:
    description: >-
      The version of the yq package to be used, defaults to latest.
      If a different version is needed, use a valid release tag from https://github.com/mikefarah/yq/tags
    required: false
    default: 'latest'
  verbose:
    description: 'Determine if the action should run verbose tasks, defaults to false.'
    required: false
    default: 'false'

runs:
  using: composite
  steps:

    - name: Download yq package
      run: wget https://github.com/mikefarah/yq/releases/download/v4.26.1/yq_linux_amd64
      shell: bash

    - name: Configure yq executable
      run: sudo mv yq_linux_amd64 /usr/bin/yq && chmod +x /usr/bin/yq
      shell: bash

branding:
  # Ref: https://haya14busa.github.io/github-action-brandings/
  # fork: https://github.com/rwaight/github-action-brandings
  icon: download
  color: blue
