name: Install yq
description: Installs the yq package for parsing YAML files
author: 'instruqt'

inputs:
  version:
    description: >-
      The version of the yq package to be used, defaults to latest.
      If a different version is needed, use a valid release tag from https://github.com/mikefarah/yq/tags
      Example versions: v4, v4.26.1, v4.47.2, v4.48.1
    required: false
    default: 'latest'
  verbose:
    description: 'Determine if the action should run verbose tasks, defaults to false.'
    required: false
    default: 'false'

runs:
  using: composite
  steps:

    - name: Validate that the runner OS is Linux
      if: ${{ runner.os != 'Linux' }}
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message
      run: |
        echo "error in the action '${{ github.action }}' at file path: '${{ github.action_path }}' "
        echo "::error file=utilities/install-yq/action.yml,title=⛔ Install yq error hint::This action supports Linux only"
        exit 1
      shell: bash

    - name: Verbose | Greet the triggering_actor
      if: inputs.verbose=='true'
      run: echo Hello ${{ github.triggering_actor }}, the verbose variable is set to true.
      shell: bash

    - name: Verbose | Print the inputs
      if: inputs.verbose=='true'
      id: verbose-print-inputs
      run: | 
        echo "::group::starting the 'verbose-print-inputs' step... "
        echo ""
        ## Print the inputs if inputs.verbose=='true'
        ## the double number signs below are for line spacing and readability only
        ##
        echo "version is set to '${{ inputs.version }}' "
        echo "verbose is set to '${{ inputs.verbose }}' "
        ##
        echo ""
        echo "finishing the 'verbose-print-inputs' step... "
        echo "::endgroup::"
      shell: bash

    - name: Download yq package
      run: wget https://github.com/mikefarah/yq/releases/download/v4.26.1/yq_linux_amd64
      shell: bash

    - name: Configure yq executable
      run: sudo mv yq_linux_amd64 /usr/bin/yq && chmod +x /usr/bin/yq
      shell: bash

branding:
  # Ref: https://haya14busa.github.io/github-action-brandings/
  # fork: https://github.com/rwaight/github-action-brandings
  icon: download
  color: blue
