name: Install yq
author: instruqt
description: Installs the yq package for parsing YAML files
group: utilities
imported: true
local:
  modifications: true
  update:
    exclusions:
      - README-examples.md
      - example-custom-notes.md
source:
  action_name: install-yq
  author: instruqt
  repo_name: examples
  repo_url: https://github.com/instruqt/examples
  current_version: 1484e628103fe8dcf60a0b70130709429b97e2c7
  latest_version: 90b782ae0fa40245140976937c69e73967799523
  override:
    use_commits: true
    latest_version_commit: 1484e628103fe8dcf60a0b70130709429b97e2c7
    latest_repo_commit: 90b782ae0fa40245140976937c69e73967799523
  update_available: false
specs:
  action_file: action.yml
  inputs: [version, verbose]
  outputs: []
  runs:
    using: composite
tests:
  _comment: reserved for future use
