name: Install yq
author: instruqt
description: Installs the yq package for parsing YAML files
group: utilities
imported: true
local:
  modifications: false
  update:
    exclusions:
      - README-examples.md
      - example-custom-notes.md
source:
  action_name: install-yq
  current_version: a63841cfbca845fbba74f532aa9cd2e0ec5cbdcf
  latest_version: 36ac5139684cd447116f7231f1e6b3a76f1b4b9d
  author: instruqt
  repo_name: examples
  repo_url: https://github.com/instruqt/examples
  override:
    use_commits: true
    latest_version_commit: a63841cfbca845fbba74f532aa9cd2e0ec5cbdcf
    latest_repo_commit: 36ac5139684cd447116f7231f1e6b3a76f1b4b9d
  update_available: false
specs:
  action_file: action.yml
  inputs: []
  outputs: []
  runs:
    using: composite
tests:
  _comment: reserved for future use
