_extends: guardrail:.github/release-drafter.yml
name-template: 'java-async-http-v$RESOLVED_VERSION'
tag-template: 'java-async-http-v$RESOLVED_VERSION'
tag-prefix: java-async-http-v
include-paths:
  - "modules/java-async-http/src/main/"
  - "project/src/main/scala/modules/javaAsyncHttp.scala"
