_extends: guardrail:.github/release-drafter.yml
name-template: 'scala-support-v$RESOLVED_VERSION'
tag-template: 'scala-support-v$RESOLVED_VERSION'
tag-prefix: scala-support-v
include-paths:
  - "modules/scala-support/src/main/"
  - "project/src/main/scala/modules/scalaSupport.scala"
