_extends: guardrail:.github/release-drafter.yml
name-template: 'java-dropwizard-v$RESOLVED_VERSION'
tag-template: 'java-dropwizard-v$RESOLVED_VERSION'
tag-prefix: java-dropwizard-v
include-paths:
  - "modules/java-dropwizard/src/main/"
  - "project/src/main/scala/modules/javaDropwizard.scala"
