_extends: guardrail:.github/release-drafter.yml
name-template: 'java-spring-mvc-v$RESOLVED_VERSION'
tag-template: 'java-spring-mvc-v$RESOLVED_VERSION'
tag-prefix: java-spring-mvc-v
include-paths:
  - "modules/java-spring-mvc/src/main/"
  - "project/src/main/scala/modules/javaSpringMvc.scala"
