_extends: guardrail:.github/release-drafter.yml
name-template: 'scala-dropwizard-v$RESOLVED_VERSION'
tag-template: 'scala-dropwizard-v$RESOLVED_VERSION'
tag-prefix: scala-dropwizard-v
include-paths:
  - "modules/scala-dropwizard/src/main/"
  - "project/src/main/scala/modules/scalaDropwizard.scala"
