_extends: guardrail:.github/release-drafter.yml
name-template: 'java-support-v$RESOLVED_VERSION'
tag-template: 'java-support-v$RESOLVED_VERSION'
tag-prefix: java-support-v
include-paths:
  - "modules/java-support/src/main/"
  - "project/src/main/scala/modules/javaSupport.scala"
