_extends: guardrail:.github/release-drafter.yml
name-template: 'scala-akka-http-v$RESOLVED_VERSION'
tag-template: 'scala-akka-http-v$RESOLVED_VERSION'
tag-prefix: scala-akka-http-v
include-paths:
  - "modules/scala-akka-http/src/main/"
  - "project/src/main/scala/modules/scalaAkkaHttp.scala"
