_extends: guardrail:.github/release-drafter.yml
name-template: 'scala-http4s-v$RESOLVED_VERSION'
tag-template: 'scala-http4s-v$RESOLVED_VERSION'
tag-prefix: scala-http4s-v
include-paths:
  - "modules/scala-http4s/src/main/"
  - "project/src/main/scala/modules/scalaHttp4s.scala"
