# attempt to adhere to a commit convention - https://commitlint.js.org/
# from https://commitlint.js.org/guides/ci-setup.html#github-actions
name: Commit manager
run-name: Check commit conventions on ${{ github.event_name }}

on: [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup node
        uses: actions/setup-node@v4

      # https://commitlint.js.org/guides/getting-started.html
      - name: Install commitlint
        run: |
          echo "starting commitlint installation. "
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest
          npm install --save-dev @commitlint/{cli,config-conventional}
          echo "commitlint has been installed"
          echo "creating 'commitlint.config.js' to use the conventional configuration. "
          echo "module.exports = { extends: ['@commitlint/config-conventional'] };" > commitlint.config.js
          echo "the 'commitlint.config.js' file has been created. "
          

      # https://commitlint.js.org/guides/local-setup.html
      - name: Install husky
        run: |
          echo "installing husky"
          npm install husky --save-dev
          echo "initialize husky"
          npx husky init
          echo "husky has been initialized"
          echo "adding commit message linting to commit-msg hook"
          echo "npx --no -- commitlint --edit \$1" > .husky/commit-msg
          echo "the 'install husky' step is now complete "

      # https://commitlint.js.org/guides/ci-setup.html#github-actions
      - name: Print versions
        run: |
          echo "::group::display file contents of current directory"
          ls -la
          echo "look for the 'commitlint.config.js' file in the output above"
          echo "::endgroup::"
          git --version
          node --version
          npm --version
          npx commitlint --version

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
