# This workflow currently runs the 'labeler' action
name: Pull Request Manager
run-name: Actions Monorepo Pull Request Manager - ${{ github.event_name }}
on:
  pull_request:
    # 'on pull_request' is used by: 'pr-labeler'
    branches: [main]

jobs:
  pr-labeler:
    name: Label pull requests
    runs-on: ubuntu-latest
    if: | 
      (github.repository_owner == 'rwaight') && (github.event_name == 'pull_request')
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Run actions/labeler
        uses: actions/labeler@v5

  # Run the 'not-repo-owner' job if the repository_owner is not correct
  not-repo-owner:
    name: Print a random note
    runs-on: ubuntu-latest
    if: (github.repository_owner != 'rwaight')
    env:
      MY_WORKFLOW_DEBUG: ${{ inputs.debug_output || 'false' }}
    steps:
      - name: Print a message based on a condition
        id: print-message
        run: |
          echo "This workflow was run in a forked repo. Unless this file is updated, none of the jobs will run. "
          echo ""
