# This workflow runs the 'Export label config' and 'Sync labels' actions and includes user input
# This file is sourced from 'infra/assets/gh_workflows'
name: Label Manager
run-name: Run ${{ github.event.action || 'label manager' }} from ${{ github.event_name }}
on: 
  # When any of the 'assets/my-labels-*.yml' files are updated
  push:
    branches:
      - main
    paths:
      - 'assets/my-labels-*.yml'
  # When called by a 'repository_dispatch' event
  repository_dispatch:
    types: [export-labels,sync-labels]
  # When called manually by a 'workflow_dispatch' event
  workflow_dispatch:
    inputs:
      export_labels:
        description: 'Export labels from repo'
        required: true
        default: true
        type: boolean
      sync_labels:
        description: 'Sync labels from config files'
        required: true
        default: false
        type: boolean
      debug_output:
        description: 'Debug output'
        required: true
        default: false
        type: boolean
  # On a schedule: every six months, at 10:00 on the first of the month
  schedule:
    - cron: '0 10 1 */6 *'  # export labels once every six months, at 10:00 on the first of the month

jobs:
  export-and-sync-labels:
    name: Export and sync repo labels
    runs-on: ubuntu-latest
    env:
      MY_WORKFLOW_DEBUG: ${{ inputs.debug_output || 'false' }}
    permissions:
      contents: write
      issues: write
    steps:
      - name: Exit workflow in forked repo
        id: check-repo-owner
        if: (github.repository_owner != 'rwaight')
        run: |
          echo "This workflow was run in a forked repo. Unless this file is updated, none of the jobs will run. "
          echo "This workflow will now exit. "
          exit 0

      # Create a GitHub App Token from actions/create-github-app-token
      # https://github.com/actions/create-github-app-token
      - name: Create an App Token for this job
        id: app-token
        if: | 
          (github.event_name=='repository_dispatch' && github.event.action=='sync-labels') || 
          (github.event_name=='workflow_dispatch' && inputs.sync_labels==true)
        # Verified creator: https://github.com/marketplace/actions/create-github-app-token
        # GitHub Action for creating a GitHub App installation access token.
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        #uses: actions/create-github-app-token@v1.10.0
        with:
          # required
          app-id: ${{ secrets.RW_ACTIONS_APP_ID }}
          private-key: ${{ secrets.RW_ACTIONS_APP_KEY }}
          # create a token for all repositories in the current owner's installation
          owner: ${{ github.repository_owner }}

      - name: Checkout files from commit tree
        # Verified creator: https://github.com/marketplace/actions/checkout
        # GitHub Action for checking out a repo
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        #uses: actions/checkout@v4.1.3
        with:
          token: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}

      - name: Configure Git Credentials if using the app token
        id: configure-git
        if: ${{ steps.app-token.outputs.token }}
        run: |
          ##
          ## Configure git to login as the RW Actions Bot.
          git config user.name rw-actions-bot[bot]
          git config user.email ${{ secrets.RW_ACTIONS_BOT_UID }}+rw-actions-bot[bot]@users.noreply.github.com

      - name: Export label config using rwaight/actions/github/export-label-config
        id: export-label-config
        if: |
          (github.event_name=='schedule' && github.event.schedule=='0 10 1 */6 *') || 
          (github.event_name=='workflow_dispatch' && inputs.export_labels==true) || 
          (github.event_name=='repository_dispatch' && github.event.action=='export-labels') ||
          (github.event_name=='repository_dispatch' && github.event.action=='sync-labels') || 
          (github.event_name=='workflow_dispatch' && inputs.sync_labels==true) ||
          (github.event_name=='push' && github.ref_name=='main') 
        uses: rwaight/actions/github/export-label-config@bb107b0a8f994fbf7d0be216086319b6a468a1da # v0.1.39
        #uses: rwaight/actions/github/export-label-config@v0.1.26
        #uses: rwaight/actions/github/export-label-config@main
        with:
          # This is needed if you're dealing with private repos.
          token: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
          # Set 'raw-result' to `true` if you want to get the raw API reponse. Defaults to `false`.
          raw-result: false
          # By default every label entry will have an `aliases` property set to an empty array.
          # It's for EndBug/label-sync, if you don't want it you can set this to `false`
          add-aliases: true

      - name: Sync labels using rwaight/actions/github/label-sync
        id: run-label-sync
        if: | 
          steps.export-label-config.outcome == 'success' && (
          (github.event_name=='repository_dispatch' && github.event.action=='sync-labels') || 
          (github.event_name=='workflow_dispatch' && inputs.sync_labels==true) ||
          (github.event_name=='push' && github.ref_name=='main') 
          )
        uses: rwaight/actions/github/label-sync@bb107b0a8f994fbf7d0be216086319b6a468a1da # v0.1.39
        #uses: rwaight/actions/github/label-sync@v0.1.26
        #uses: rwaight/actions/github/label-sync@main
        with:
          config-file: |
            assets/my-labels-core.yml
            assets/my-labels-actions.yml
            assets/my-labels-versioning.yml
          ## use the repo's local labels in the 'assets/' directory
          ##  https://raw.githubusercontent.com/rwaight/actions/main/assets/my-labels-core.yml
          ##  https://raw.githubusercontent.com/rwaight/actions/main/assets/my-labels-actions.yml
          ##  https://raw.githubusercontent.com/rwaight/actions/main/assets/my-labels-versioning.yml
          ## #
          ## # The 'request-token' parameter is needed so the remote config-file values can be accessed
          ## request-token: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
          # If you want to delete any additional label, set this to true
          delete-other-labels: true
          # If you want the action just to show you the preview of the changes, without actually editing the labels, set this to true
          dry-run: false
          # You can change the token used to change the labels, this is the default one
          token: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}

      - name: Run workflow debug
        id: run-workflow-debug
        if: env.MY_WORKFLOW_DEBUG=='true'
        run: |
          echo "workflow debug was set to true... you should probably put something here for debug purposes. "
          echo ""
          echo "The GitHub event_name is: ${{ github.event_name }}"
          echo "The GitHub ref is: ${{ github.ref }}"
          echo "The GitHub ref_name is: ${{ github.ref_name }}"
          echo ""
          echo "For more information, see the GitHub Actions Contexts docs, which are located at: "
          echo "https://docs.github.com/en/actions/learn-github-actions/contexts#github-context"
          echo "The 'run-workflow-debug' step is now complete. "
        continue-on-error: true
