# This workflow runs the 'Export label config' and 'Sync labels' actions and includes user input
name: Reusable Label Manager
run-name: Run ${{ github.event.action || 'label manager' }} from ${{ github.event_name }}
on:
  # 'workflow_call' will allow other GitHub workflows to call this workflow
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
  # if we need to define inputs, then we need to review the docs in the link below
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-of-onworkflow_callinputs
  workflow_call:
    # Inputs and secrets: # https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
    # Inputs:             # https://docs.github.com/en/enterprise-cloud@latest/actions/creating-actions/metadata-syntax-for-github-actions#inputs
    inputs:
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs
      export_labels:
        description: 'Export labels from repo'
        required: true
        default: true
        type: boolean
      sync_labels:
        description: 'Sync labels from config files'
        required: true
        default: false
        type: boolean
      debug_output:
        description: 'Debug output'
        required: true
        default: false
        type: boolean

    secrets:
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callsecrets
      my_actions_app_id:
        description: ', this is passed from the caller workflow. '
        required: false
      my_actions_app_key:
        description: ', this is passed from the caller workflow. '
        required: false
      my_github_token:
        description: ', this is passed from the caller workflow. '
        required: false

jobs:
  test-workflow-call:
    runs-on: ubuntu-latest
    if: github.event_name=='workflow_call'
    env:
      MY_WORKFLOW_DEBUG: ${{ inputs.debug_output || 'false' }}
    steps:
      - name: Exit workflow in forked repo
        id: check-repo-owner
        if: (github.repository_owner != 'rwaight')
        run: |
          echo "This workflow was run in a forked repo. Unless this file is updated, none of the jobs will run. "
          echo "This workflow will now exit. "
          exit 0

      - name: A workflow_call event was received
        run: |
          echo "a 'workflow_call' event was triggered .. "
          echo ""
          echo "the event 'action' value is: '${{ github.event.action }}'"
          echo ""
          echo "the 'client_payload' value of the 'export' key is: '${{ github.event.client_payload.export }}'"
          echo "if the 'export' value above is empty, then look at the context below.. "

      - name: Debug | Output the runner environment and GitHub context
        #if: env.MY_WORKFLOW_DEBUG=='true'
        run: | 
          echo "::group::Runner Environment"
          echo "## Runner Environment"
          env | sort
          echo "\n"
          echo "::endgroup::"
          echo ""
          echo "::group::GitHub context"
          echo "## GitHub context"
          echo "$GITHUB_CONTEXT"
          echo "\n"
          echo "::endgroup::"
          echo ""
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: README about GitHub Actions Contexts
        #if: env.MY_WORKFLOW_DEBUG=='true'
        run: | 
          echo "For more information about GitHub Actions Contexts, see the docs that are located at: "
          echo "https://docs.github.com/en/actions/learn-github-actions/contexts#github-context"

      - name: README about GitHub Actions Inputs
        #if: env.MY_WORKFLOW_DEBUG=='true'
        run: |
          echo "You should read this changelog from the GitHub blog about using inputs, "
          echo "the link to the blog is: "
          echo "https://github.blog/changelog/2022-06-10-github-actions-inputs-unified-across-manual-and-reusable-workflows/"
          echo ""
          echo "also review the using the inputs context in github actions docs, the link is: "
          echo "https://docs.github.com/en/actions/learn-github-actions/contexts#inputs-context"
          echo ""

  reuse-export-and-sync-labels:
    name: Export and sync repo labels
    #name: Export repo label configuration
    runs-on: ubuntu-latest
    # if: | 
    #   (github.event_name=='schedule' && github.event.schedule=='0 10 1 */6 *') || 
    #   (github.event_name=='workflow_dispatch' && inputs.export_labels==true) || 
    #   (github.event_name=='repository_dispatch' && github.event.client_payload.export=='true') || 
    #   (github.event_name=='repository_dispatch' && github.event.action=='export-labels') || 
    #   (github.event_name=='repository_dispatch' && github.event.action=='sync-labels') || 
    #   (github.event_name=='workflow_dispatch' && inputs.sync_labels==true)
    env:
      MY_WORKFLOW_DEBUG: ${{ inputs.debug_output || 'false' }}
    permissions:
      contents: write
      issues: write
    steps:
      - name: Exit workflow in forked repo
        id: check-repo-owner
        if: (github.repository_owner != 'rwaight')
        run: |
          echo "This workflow was run in a forked repo. Unless this file is updated, none of the jobs will run. "
          echo "This workflow will now exit. "
          exit 0

      # - name: Checkout files from commit tree
      #   id: checkout-without-token
      #   if: |
      #     (github.event_name=='schedule' && github.event.schedule=='0 10 1 */6 *') || 
      #     (github.event_name=='workflow_dispatch' && inputs.export_labels==true) || 
      #     (github.event_name=='repository_dispatch' && github.event.action=='export-labels')
      #   uses: actions/checkout@v4

      # https://github.com/actions/create-github-app-token
      - name: Create a GitHub App Token from actions/create-github-app-token
        id: app-token
        if: | 
          (github.event_name=='repository_dispatch' && github.event.action=='sync-labels') || 
          (github.event_name=='workflow_dispatch' && inputs.sync_labels==true) ||
          (github.event_name=='workflow_call' && inputs.sync_labels==true)
        #uses: actions/create-github-app-token@v1
        uses: actions/create-github-app-token@f2acddfb5195534d487896a656232b016a682f3c
        with:
          # required
          app-id: ${{ secrets.my_actions_app_id }}
          private-key: ${{ secrets.my_actions_app_key }}
          # create a token for all repositories in the current owner's installation
          owner: ${{ github.repository_owner }}

      - name: Checkout files from commit tree
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token || secrets.my_github_token }}

      # - name: Checkout files from commit tree
      #   id: checkout-with-token
      #   if: | 
      #     (github.event_name=='repository_dispatch' && github.event.action=='sync-labels') || 
      #     (github.event_name=='workflow_dispatch' && inputs.sync_labels==true)
      #   uses: actions/checkout@v4
      #   with:
      #     token: ${{ steps.app-token.outputs.token }}

      - name: Export label config using rwaight/actions/github/export-label-config
        id: export-label-config
        if: |
          (github.event_name=='schedule' && github.event.schedule=='0 10 1 */6 *') || 
          (github.event_name=='workflow_dispatch' && inputs.export_labels==true) || 
          (github.event_name=='repository_dispatch' && github.event.action=='export-labels') ||
          (github.event_name=='repository_dispatch' && github.event.action=='sync-labels') || 
          (github.event_name=='workflow_dispatch' && inputs.sync_labels==true)
        #uses: rwaight/actions/github/export-label-config@v1   # can use version specific or main
        uses: rwaight/actions/github/export-label-config@main  # can use version specific or main
        with:
          # This is needed if you're dealing with private repos.
          #token: ${{ secrets.MY_ACTIONS_TOKEN }}
          #token: ${{ secrets.GITHUB_TOKEN }}
          # Set 'raw-result' to `true` if you want to get the raw API reponse. Defaults to `false`.
          raw-result: false
          # By default every label entry will have an `aliases` property set to an empty array.
          # It's for EndBug/label-sync, if you don't want it you can set this to `false`
          add-aliases: true

      - name: Sync labels using rwaight/actions/github/label-sync
        id: run-label-sync
        if: | 
          steps.export-label-config.outcome == 'success' && (
          (github.event_name=='repository_dispatch' && github.event.action=='sync-labels') || 
          (github.event_name=='workflow_dispatch' && inputs.sync_labels==true)
          )
        #uses: rwaight/actions/github/label-sync@v1 # can use version specific or main
        uses: rwaight/actions/github/label-sync@main # can use version specific or main
        with:
          config-file: |
            https://raw.githubusercontent.com/rwaight/actions/main/assets/my-labels-core.yml
            https://raw.githubusercontent.com/rwaight/actions/main/assets/my-labels-versioning.yml
          ##  automations/my-labels-core.yml
          ##  automations/my-labels-versioning.yml
          #
          # The 'request-token' parameter is needed so the remote config-file values can be accessed
          #request-token: ${{ secrets.GITHUB_TOKEN }}
          #request-token: ${{ steps.app-token.outputs.token }}
          request-token: ${{ steps.app-token.outputs.token || secrets.my_github_token }}
          # If you want to delete any additional label, set this to true
          delete-other-labels: true
          # If you want the action just to show you the preview of the changes, without actually editing the labels, set this to true
          dry-run: false
          # You can change the token used to change the labels, this is the default one
          #token: ${{ secrets.GITHUB_TOKEN }}
          #token: ${{ steps.app-token.outputs.token }}
          token: ${{ steps.app-token.outputs.token || secrets.my_github_token }}

      - name: Run workflow debug
        id: run-workflow-debug
        if: env.MY_WORKFLOW_DEBUG=='true'
        run: |
          echo "workflow debug was set to true... you should probably put something here for debug purposes. "
          echo ""
          echo "The GitHub event_name is: ${{ github.event_name }}"
          echo "The GitHub ref is: ${{ github.ref }}"
          echo "The GitHub ref_name is: ${{ github.ref_name }}"
          echo ""
          echo "For more information, see the GitHub Actions Contexts docs, which are located at: "
          echo "https://docs.github.com/en/actions/learn-github-actions/contexts#github-context"
          echo "The 'run-workflow-debug' step is now complete. "
        continue-on-error: true
