# from https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
name: Create and publish a Docker image

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ['release']
  release:
    types: [published]

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    name: Build and push ${{ matrix.name }} image
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      # 
    strategy:
      matrix:
        action: [render-template, pr-label-checker, git-describe-semver]
        # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-expanding-configurations
        # use 'include' to specify additional variables
        include:
          - action: render-template
            name: render-template
            description: "Renders file based on template and passed variables"
            dir: utilities/render-template
            go-version: 1.17.x
            #test: "-e DOCKER_TEST_ONLY=true"
          - action: pr-label-checker
            name: label-checker
            description: "Checks pull requests for given labels"
            dir: github/label-checker
            go-version: 1.21.x
            #test: "-e DOCKER_TEST_ONLY=true"
          - action: git-describe-semver
            name: git-describe-semver
            description: "Produces semver compatible versions that follow to semver sorting rules"
            dir: git/git-describe-semver
            go-version: 1.19.x
            #test: "-e DOCKER_TEST_ONLY=true"
    # Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
    env:
      REGISTRY: ghcr.io
      #IMAGE_NAME: ${{ github.repository }}
      IMAGE_NAME: ${{ github.repository }}/${{ matrix.name }}
      #IMAGE_NAME: ${{ matrix.name }}
    defaults:
      run:
        # set the the runners 'working-directory' to '${{ matrix.dir }}'
        # https://docs.github.com/en/actions/using-jobs/setting-default-values-for-jobs#setting-default-shell-and-working-directory
        working-directory: ./${{ matrix.dir }}
    steps:
      - name: Checkout repository
        # Verified creator: https://github.com/marketplace/actions/checkout
        # GitHub Action for checking out a repo
        #uses: actions/checkout@v4
        uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0
          fetch-tags: true
          #token: ${{ secrets.GITHUB_TOKEN }}
          sparse-checkout: |
            .github
            ${{ matrix.dir }}

      - name: Display structure of files in working directory
        #if: env.MY_WORKFLOW_DEBUG=='true'
        run: ls -R

      - name: Setup Go environment
        if: ${{ matrix.go-version }}
        # Verified creator: https://github.com/marketplace/actions/setup-go-environment
        # Set up your GitHub Actions workflow with a specific version of Go
        #uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        uses: actions/setup-go@v4.1.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install QEMU static binaries
        # Verified creator: https://github.com/marketplace/actions/docker-setup-qemu
        # GitHub Action to install QEMU static binaries
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3

      - name: Setup Docker Buildx
        # Verified creator: https://github.com/marketplace/actions/docker-setup-buildx
        # GitHub Action to set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb

      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Log in to the ${{ env.REGISTRY }} container registry
        # Verified creator: https://github.com/marketplace/actions/docker-login
        # GitHub Action to login against a Docker registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          #registry: ghcr.io
          registry: ${{ env.REGISTRY }}
          #username: ${{ github.actor }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # This step uses [docker/metadata-action](https://github.com/docker/metadata-action#about) to extract tags and labels that will be applied to the specified image. The `id` "meta" allows the output of this step to be referenced in a subsequent step. The `images` value provides the base name for the tags and labels.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        # Verified creator: https://github.com/marketplace/actions/docker-metadata-action
        # GitHub Action to extract metadata (tags, labels) from Git reference and GitHub events for Docker 
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha

      # This step uses the `docker/build-push-action` action to build the image, based on your repository's `Dockerfile`. If the build succeeds, it pushes the image to GitHub Packages.
      # It uses the `context` parameter to define the build's context as the set of files located in the specified path. For more information, see "[Usage](https://github.com/docker/build-push-action#usage)" in the README of the `docker/build-push-action` repository.
      # It uses the `tags` and `labels` parameters to tag and label the image with the output from the "meta" step.
      - name: Build and push Docker image
        id: push
        # Verified creator: https://github.com/marketplace/actions/build-and-push-docker-images
        # GitHub Action to build and push Docker images with Buildx
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        # Skip running on forks or Dependabot since neither has access to secrets
        if: |
          (github.repository == 'rwaight/actions') &&
          (github.actor!= 'dependabot[bot]') &&
          (contains(github.head_ref, 'dependabot-') == false)
        with:
          context: .
          #context: "{{defaultContext}}:${{ matrix.dir }}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          #platforms: linux/amd64,linux/arm64
          platforms: linux/amd64

      # This step generates an artifact attestation for the image, which is an unforgeable statement about where and how it was built. It increases supply chain security for people who consume the image. For more information, see "[AUTOTITLE](/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds)." 
      - name: Generate artifact attestation
        # Verified creator: https://github.com/marketplace/actions/attest-build-provenance
        # Action for generating build provenance attestations for workflow artifacts
        uses: actions/attest-build-provenance@v1.0.0
        # Skip running on forks or Dependabot since neither has access to secrets
        if: |
          (github.repository == 'rwaight/actions') &&
          (github.actor!= 'dependabot[bot]') &&
          (contains(github.head_ref, 'dependabot-') == false)
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Print outputs from the push step
        id: print-image-info
        if: steps.push.outcome == 'success'
        run: |
          echo "The image id is: ${{ steps.push.outputs.imageid }}"
          echo "The image digest is ${{ steps.push.outputs.digest }}"
          echo "The image metadata is: "
          echo "${{ fromJSON(steps.push.outputs.metadata) }}"
          echo ""
