# from https://github.com/release-flow/keep-a-changelog-action/blob/v3.0.0/.github/workflows/prepare-release.yml
# this should be moved into the 'release-manager' workflow
name: 'Test - Prepare release PR'
#name: '[autorelease] Prepare release PR'
run-name: 'Prepare release PR - ${{ inputs.release-type }}'

on: 
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type'
        type: choice
        required: true
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease
        default: patch
      preid:
        description: 'Pre-release identifier (only for pre-release builds)'
        default: rc
        required: false

permissions:
  contents: read
  #contents: write
  issues: write
  pull-requests: write

jobs:
  changelog:
    name: Update changelog and create PR
    runs-on: ubuntu-latest
    steps:
      - name: Exit workflow in forked repo
        id: check-repo-owner
        if: (github.repository_owner != 'rwaight')
        run: |
          echo "This workflow was run in a forked repo. Unless this file is updated, none of the jobs will run. "
          echo "This workflow will now exit. "
          exit 0

      - name: Create a GitHub App Token
        # Verified creator: https://github.com/marketplace/actions/create-github-app-token
        # GitHub Action for creating a GitHub App installation access token.
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1.10.3
        #uses: actions/create-github-app-token@v1.10.0
        id: app-token
        with:
          # required
          app-id: ${{ secrets.RW_ACTIONS_APP_ID }}
          private-key: ${{ secrets.RW_ACTIONS_APP_KEY }}

      - name: Checkout files from commit tree
        # Verified creator: https://github.com/marketplace/actions/checkout
        # GitHub Action for checking out a repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        #uses: actions/checkout@v4.1.3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.app-token.outputs.token }}

      # not configuring releasebot at this time
      #     releasebot info:
      #       https://github.com/apps/conventional-release-bot
      #       
      # - uses: tibdex/github-app-token@v2
      #   id: generate-token
      #   with:
      #     app_id: ${{ secrets.RELEASEBOT_APP_ID }}
      #     private_key: ${{ secrets.RELEASEBOT_PRIVATE_KEY }}

      - name: 'Ensure actions:autorelease label exists'
        run: |
          LABEL=$(gh api repos/$GITHUB_REPOSITORY/labels --jq '.[] | select(.name=="actions:autorelease")')
          if [[ -z "$LABEL" ]]; then
            echo "Creating 'actions:autorelease' label"
            gh api --silent repos/$GITHUB_REPOSITORY/labels -f name="actions:autorelease" -f color="baa938" -f description="This is an automatically-created PR to trigger a release"
          else
            echo "the 'actions:autorelease' label exists"
          fi
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}

      # https://github.com/release-flow/keep-a-changelog-action
      - name: Get latest release info
        id: query-latest-release
        continue-on-error: true
        uses: rwaight/actions/git/keep-a-changelog-action@130cf7b531a919de678759798a1aee9474dbeb47 # v0.1.34
        #uses: rwaight/actions/git/keep-a-changelog-action@v0.1.26
        #uses: rwaight/actions/git/keep-a-changelog-action@main
        with:
          # https://github.com/release-flow/keep-a-changelog-action/blob/main/docs/query.md
          command: query
          version: latest

      - name: Print latest release info
        id: print-latest-release
        run: |
          echo "Latest release information: "
          echo "Version: ${{ steps.query-latest-release.outputs.version }}"
          echo "Date: ${{ steps.query-latest-release.outputs.release-date }}"
          echo "Release notes: "
          echo "${{ steps.query-latest-release.outputs.release-notes }}"
          echo ""

      # https://github.com/release-flow/keep-a-changelog-action
      - name: Get unreleased changes release info
        id: query-unreleased-changes
        continue-on-error: true
        uses: rwaight/actions/git/keep-a-changelog-action@130cf7b531a919de678759798a1aee9474dbeb47 # v0.1.34
        #uses: rwaight/actions/git/keep-a-changelog-action@v0.1.26
        #uses: rwaight/actions/git/keep-a-changelog-action@main
        with:
          # https://github.com/release-flow/keep-a-changelog-action/blob/main/docs/query.md
          command: query
          version: unreleased

      - name: Print unreleased changes info
        id: print-unreleased-changes
        run: |
          echo "Unreleased changes information: "
          echo "Version: ${{ steps.query-unreleased-changes.outputs.version }}"
          echo "Date: ${{ steps.query-unreleased-changes.outputs.release-date }}"
          echo "Release notes: "
          echo "${{ steps.query-unreleased-changes.outputs.release-notes }}"
          echo ""

      # https://github.com/release-flow/keep-a-changelog-action
      - name: Get latest-or-unreleased changes release info
        id: query-latest-or-unreleased-changes
        continue-on-error: true
        uses: rwaight/actions/git/keep-a-changelog-action@130cf7b531a919de678759798a1aee9474dbeb47 # v0.1.34
        #uses: rwaight/actions/git/keep-a-changelog-action@v0.1.26
        #uses: rwaight/actions/git/keep-a-changelog-action@main
        with:
          # https://github.com/release-flow/keep-a-changelog-action/blob/main/docs/query.md
          command: query
          version: latest-or-unreleased

      - name: Print latest-or-unreleased changes info
        id: print-latest-or-unreleased-changes
        run: |
          echo "latest-or-unreleased changes information: "
          echo "Version: ${{ steps.query-latest-or-unreleased-changes.outputs.version }}"
          echo "Date: ${{ steps.query-latest-or-unreleased-changes.outputs.release-date }}"
          echo "Release notes: "
          echo "${{ steps.query-latest-or-unreleased-changes.outputs.release-notes }}"
          echo ""

      - name: Need to write to the unreleased section here
        id: notice-about-changelog
        run: |
          echo "Need to actually write to the unreleased section of the changelog here. "

      # https://github.com/release-flow/keep-a-changelog-action
      - name: Update changelog using inputs.release-type (${{ github.event.inputs.release-type }})
        id: update-changelog
        uses: rwaight/actions/git/keep-a-changelog-action@130cf7b531a919de678759798a1aee9474dbeb47
        #uses: rwaight/actions/git/keep-a-changelog-action@v0.1.34
        #uses: rwaight/actions/git/keep-a-changelog-action@main
        with:
          # https://github.com/release-flow/keep-a-changelog-action/blob/main/docs/bump.md
          command: bump
          keep-unreleased-section: true
          # commenting out 'keep-unreleased-section: true' did not fix having blank release notes
          # going to comment out the 'query' steps prior to the 'bump' step
          # going to try to comment out the 'fail-on-empty-release-notes' option next
          version: ${{ github.event.inputs.release-type }}
          preid: ${{ github.event.inputs.preid }}
          fail-on-empty-release-notes: false

      - name: Print output from update-changelog
        id: print-update-changelog
        run: |
          echo "Output from the 'update-changelog' step: "
          echo "Version: ${{ steps.update-changelog.outputs.version }}"
          echo "Date: ${{ steps.update-changelog.outputs.release-date }}"
          echo "Release notes: "
          echo "${{ steps.update-changelog.outputs.release-notes }}"
          echo ""

      - name: Print notice that no pr is being created
        id: print-notice-no-pr
        run: |
          echo "::notice title=Release PR NOT Prepared::A release PR WAS NOT created, please review the output of the workflow"

      # - name: Create Pull Request
      #   id: create-release-pr
      #   #uses: peter-evans/create-pull-request@v6
      #   uses: peter-evans/create-pull-request@70a41aba780001da0a30141984ae2a0c95d8704e
      #   with:
      #     commit-message: 'chore: Update changelog for release ${{ steps.update-changelog.outputs.version }}'
      #     #committer: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>' # this is the default
      #     #committer: 'releasebot <noreply@github.com>'
      #     #committer: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>' # this is the default
      #     branch: 'autorelease/${{ steps.update-changelog.outputs.version }}'
      #     title: '[autorelease] Release ${{ steps.update-changelog.outputs.version }}'
      #     # Be careful of newlines here. We need to use the literal block chomping style (|) so that the
      #     # contents of the release notes don't get chomped. See https://yaml-multiline.info/
      #     body: |
      #       **This PR was created automatically by the rw-actions-bot**

      #       **:warning: Approving this PR will trigger a workflow that generates a draft release. You need to publish this release when you are happy with it.**

      #       The changes in this PR prepare for release ${{ steps.update-changelog.outputs.version }}. The release notes are:

      #       ---

      #       ${{ steps.update-changelog.outputs.release-notes }}
      #     #labels: actions:autorelease, version:${{ github.event.inputs.release-type }}
      #     labels: actions:autorelease, skip-changelog
      #     #token: ${{ steps.generate-token.outputs.token }}
      #     #token: ${{ secrets.GITHUB_TOKEN }}
      #     token: ${{ steps.app-token.outputs.token }}

      # - name: Output summary
      #   run: |
      #     echo "::notice title=Release PR Prepared::A release PR has been created, please merge it to continue with the release process: ${{ steps.create-release-pr.outputs.pull-request-url }}"
