# This IS A TEST workflow to run other workflows based on changes within the repo
name: Infra Copycat
run-name: Run copycat on ${{ github.event_name }}
on: 
  push:
    branches: # 'on push' to 'main' is used by: 'dispatch-label-manager'
      - main
    paths:
      - 'assets/copycat/**'
  # pull_request:
  #   branches: [ main ]
  #   #paths:
  #   #  - 'assets/my-labels-*.yml'
  #   types: [ closed ]
  workflow_dispatch:
    inputs:
      verbose_output:
        description: 'Verbose output'
        required: true
        default: false
        type: boolean

env:
  VERBOSE_WORKFLOW: ${{ inputs.verbose_output || 'false' }}
  INFRA_SOURCE: rwaight/actions
  INFRA_BOT: rw-actions-bot[bot]

jobs:
  copycat-assets:
    name: copycat assets to ${{ github.repository_owner }}/${{ matrix.repo }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        repo: 
          #- 'actions'
          - 'test-actions'
          - 'rwaight.github.io'
          #- 'hosts'
          #- 'WindowsAutomation'
          #- 'actions-run-markserv'
        # use 'include' to specify additional variables
        include:
          - repo: test-actions
            base: main
          - action: rwaight.github.io
            base: master
    steps:
      - name: Create an App Token
        # Verified creator: https://github.com/marketplace/actions/create-github-app-token
        # GitHub Action for creating a GitHub App installation access token.
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1.10.3
        #uses: actions/create-github-app-token@v1.10.0
        id: app-token
        with:
          # required
          app-id: ${{ secrets.RW_ACTIONS_APP_ID }}
          private-key: ${{ secrets.RW_ACTIONS_APP_KEY }}
          # create a token for all repositories in the current owner's installation
          owner: ${{ github.repository_owner }}
          #repositories: "actions,${{ matrix.repo }}"

      - name: Checkout files from the 'actions' repo
        id: checkout-actions-repo
        # Verified creator: https://github.com/marketplace/actions/checkout
        # GitHub Action for checking out a repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        #uses: actions/checkout@v4.1.3
        with:
          token: ${{ steps.app-token.outputs.token }}
          #path: rw-actions
          sparse-checkout: |
            .github
            assets/copycat/

      - name: Verbose | File structure before the copycat actions
        #if: env.VERBOSE_WORKFLOW=='true'
        run: |
          echo "this is the current working directory, it was not set to anything specific ... "
          pwd
          echo "below are the file contents... "
          ls -R

##### do not use the copycat action with the create pull request action... they don't play nice
## instead, just use the 'run' block to copy the files we want to copy to whatever folder
## that means, checkout both repos, then copy files from the 'actions' repo to the proper 'matrix.repo' directory
## THEN use the create-pull-request action to add and commit the copied files...

      - name: Run the copycat action
        uses: rwaight/actions/utilities/copycat@130cf7b531a919de678759798a1aee9474dbeb47 # v0.1.34
        #uses: rwaight/actions/utilities/copycat@v0.1.26
        #uses: rwaight/actions/utilities/copycat@main
        id: copycat
        # see https://github.com/rwaight/actions/blob/main/utilities/copycat/copycat_README.md#usage for more detail
        with:
          #github-token: ${{ steps.app-token.outputs.token }}
          # currently only supports the (classic) personal access tokens
          # does not work#personal_token: ${{ steps.app-token.outputs.token }}
          personal_token: ${{ secrets.RW_COPYCAT_TOKEN }}
          #try next#personal_token: ${{ secrets.GITHUB_TOKEN }}
          #try next#personal_token: ${{ github.token }}
          file_filter: '*.yml'
          exclude: '.github/*'
          # do NOT empty the 'dst_path' before copying
          clean: false
          #src_path: rw-actions/assets/copycat/
          src_path: assets/copycat/
          src_branch: main
          dst_path: .github/workflows/
          dst_branch: copycat-assets
          dst_owner: ${{ github.repository_owner }}
          dst_repo_name: ${{ matrix.repo }}
          #username: rw-actions-bot[bot]
          username: ${{ env.INFRA_BOT }}
          #email: ${{ secrets.RW_ACTIONS_BOT_UID }}+rw-actions-bot[bot]@users.noreply.github.com
          email: ${{ secrets.RW_ACTIONS_BOT_UID }}+${{ env.INFRA_BOT }}@users.noreply.github.com
          commit_message: "chore: update copycat assets from ${{ env.INFRA_SOURCE }}"

      - name: Verbose | File structure after the copycat actions
        #if: env.VERBOSE_WORKFLOW=='true'
        run: |
          echo "this is the current working directory... "
          pwd
          echo "below are the file contents... "
          ls -R

      - name: Verbose | Need to delete the 'actions' repo directory
        #if: env.VERBOSE_WORKFLOW=='true'
        run: |
          echo "Need to delete the 'actions' repo directory now... "

      - name: Checkout the 'copycat-assets' branch from the '${{ matrix.repo }}' repo
        id: checkout-matrix-repo
        # Verified creator: https://github.com/marketplace/actions/checkout
        # GitHub Action for checking out a repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        #uses: actions/checkout@v4.1.3
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: ${{ github.repository_owner }}/${{ matrix.repo }}
          ref: copycat-assets
          path: ${{ matrix.repo }}
          #fetch-depth: 0

      - name: Verbose | File structure after checkout of the second repo
        #if: env.VERBOSE_WORKFLOW=='true'
        working-directory: ./actions
        run: |
          echo "this is the current working directory, it was set to './actions' ... "
          pwd
          echo "below are the file contents... "
          ls -R

      - name: Verbose | Status of the ${{ matrix.repo }} repo
        #if: env.VERBOSE_WORKFLOW=='true'
        working-directory: ./${{ matrix.repo }}
        run: |
          echo "this is the current status of the ${{ matrix.repo }} repo... "
          git status
          echo ""
          echo "the results of 'git status' are above"

      - name: Verbose | File structure after checkout of the ${{ matrix.repo }} repo
        #if: env.VERBOSE_WORKFLOW=='true'
        #working-directory: ./${{ matrix.repo }}
        run: |
          echo "this is the current working directory... "
          pwd
          echo "below are the file contents... "
          ls -R

      # https://github.com/peter-evans/create-pull-request/blob/main/README.md
      - name: Create pull request in ${{ matrix.repo }}
        id: create-copycat-pr
        uses: rwaight/actions/github/create-pull-request@130cf7b531a919de678759798a1aee9474dbeb47 # v0.1.34
        #uses: rwaight/actions/github/create-pull-request@v0.1.26
        #uses: rwaight/actions/github/create-pull-request@main
        with:
          path: ${{ matrix.repo }}/
          #add-paths: |
          #  .github/workflows/*.yml
          branch: 'copycat-assets'
          #branch: 'infra-copycat-assets'
          branch-suffix: short-commit-hash
          # https://github.com/peter-evans/create-pull-request#alternative-strategy---always-create-a-new-pull-request-branch
          # probably do not need this since we have the proper 'ref' set in the 'checkout-matrix-repo' step #base: 'main'
          base: '${{ matrix.base }}'
          title: '[infra-copycat] update copycat assets from ${{ env.INFRA_SOURCE }}'
          author: '${{ env.INFRA_BOT }} <${{ secrets.RW_ACTIONS_BOT_UID }}+${{ env.INFRA_BOT }}@users.noreply.github.com>'
          #committer: 'rw-actions-bot[bot] <${{ secrets.RW_ACTIONS_BOT_UID }}+rw-actions-bot[bot]@users.noreply.github.com>'
          committer: '${{ env.INFRA_BOT }} <${{ secrets.RW_ACTIONS_BOT_UID }}+${{ env.INFRA_BOT }}@users.noreply.github.com>'
          commit-message: 'chore(copycat): update assets from ${{ env.INFRA_SOURCE }}'
          # Be careful of newlines here. We need to use the literal block chomping style (|) so that the
          # contents of the release notes don't get chomped. See https://yaml-multiline.info/
          body: |
            **This PR was created automatically by the test-infra-copycat workflow**
          labels: type:chore, impacts:assets
          token: ${{ steps.app-token.outputs.token }}
          assignees: rwaight
          reviewers: rwaight
          #team-reviewers: |
          #  developers
          draft: true
  
      - name: Output summary
        run: |
          echo "::notice title=Copycat PR Prepared::A copycat PR has been created in ${{ matrix.repo }}, please merge it to update the asset files: ${{ steps.create-copycat-pr.outputs.pull-request-url }}"
