# This workflow currently runs the 'stale-issue-and-pr' action
# This file is sourced from the 'infra' repo, the file location is: 'infra/assets/gh_workflows/triage-stale.yml'
name: Triage stale records
run-name: Triage stale issues and PRs - ${{ github.event_name }}
on:
  workflow_dispatch:
    inputs:
      triage_issues:
        description: 'Check for stale issues and PRs'
        required: true
        default: false
        type: boolean
      debug_output:
        description: 'Debug output'
        required: true
        default: false
        type: boolean
  # 'on schedule' is used by: 'stale-issue-and-pr'
  schedule:
    - cron: '15 14 1 */1 *' # At 14:15 on day-of-month 1 in every month, used by 'stale-issue-and-pr'
    #- cron: '15 14 * * 2' # At 2:15pm UTC every Tuesday, used by 'stale-issue-and-pr'

env:
  VERBOSE_WORKFLOW: ${{ inputs.verbose_output || 'true' }}
  # the bot name without the '[bot]' suffix
  GH_LOCAL_BOT_NAME: 'rw-actions-bot'
  # the owner of the repo, used in conditionals below
  GH_OWNER: rwaight
  # the schedule for the workflow
  GH_SCHEDULE: '15 14 1 */1 *'

jobs:
  # Run 'Triage Issues and PRs', but only: At 2:15pm UTC every Tuesday; or manual (workflow_dispatch)
  stale-issue-and-pr:
    name: Check for stale issues and PRs
    if: | 
      (github.event_name=='schedule' && github.event.schedule=='15 14 1 */1 *') || 
      (github.event_name=='workflow_dispatch' && inputs.triage_issues==true)
    runs-on: ubuntu-latest
    # https://github.com/actions/stale?tab=readme-ov-file#recommended-permissions
    permissions:
      issues: write
      pull-requests: write
    # From GitHub: https://github.com/marketplace/actions/close-stale-issues
    # See https://github.com/actions/stale#readme for configuration options
    steps:

      - name: Exit workflow in forked repo
        id: check-repo-owner
        if: ${{ github.repository_owner != env.GH_OWNER }}
        run: |
          echo "This workflow was run in a forked repo. Unless this file is updated, none of the jobs will run. "
          echo "This workflow will now fail and exit. "
          echo "::error title=⛔ error in the '${{ github.workflow }}' workflow hint::This workflow was run in a forked repo"
          exit 1

      - name: Triage issues using actions/stale
        # Verified creator: https://github.com/marketplace/actions/close-stale-issues
        # Marks issues and pull requests that have not had recent interaction
        uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        with:
          days-before-close: -1 # do not close issues or PRs
          days-before-issue-stale: 90
          stale-issue-label: 'triage:stale'
          stale-issue-message: >-
            This issue has not been updated in a while and is being labeled as `triage:stale`.

            It would be helpful to take a look at the issue and confirm it is still relevant.
          #days-before-issue-close: -1 # do not close issues when deployed to production
          #close-issue-message: 'This issue has not been updated in a while and is being closed.'
          days-before-pr-stale: 21
          stale-pr-label: 'triage:stale'
          stale-pr-message: >-
            This Pull Request (PR) has not been updated in a while and is being labeled as `triage:stale`.

            It would be helpful to review the PR and confirm it is still relevant.
          remove-stale-when-updated: true
          labels-to-remove-when-unstale: 'triage:stale'
          operations-per-run: 100
          #repo-token: ${{ secrets.MY_ACTIONS_TOKEN }}

